/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all applications
         * @description Returns every application on the mesh, including inactive ones. The public catalog only exposes active applications.
         */
        get: operations["list-applications"];
        put?: never;
        /**
         * Register an application
         * @description Registers a new application. The slug must match the certificate CN of the service's mesh nodes.
         */
        post: operations["create-application"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search applications
         * @description Query applications with text search over name and slug, status faceting, date-range filters, sorting, and pagination. An empty body returns page 1, size 25, sorted updated_at desc, unfiltered.
         */
        post: operations["search-applications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an application
         * @description Fetches a single application by ID, including its current status.
         */
        get: operations["get-application"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update an application
         * @description Updates an application's name and status. Set status to 'inactive' to soft-disable it — there is no hard delete.
         */
        patch: operations["update-application"];
        trace?: never;
    };
    "/applications/{app_id}/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user grants for an application in a tenant
         * @description Returns the per-user grants for an application within a tenant. Pass tenant_id as a query parameter.
         */
        get: operations["list-grants"];
        put?: never;
        /**
         * Grant a user access to an application
         * @description Grants a user access to an application within a tenant, with explicit roles/scopes and an optional tier. Explicit scopes are admin-assigned; tier scopes are inherited.
         */
        post: operations["create-grant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/grants/{tenant_id}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a user's grant
         * @description Removes a user's access to an application within a tenant.
         */
        delete: operations["revoke-grant"];
        options?: never;
        head?: never;
        /**
         * Update a user's grant
         * @description Replaces a grant's roles and scopes and sets (or clears) its tier.
         */
        patch: operations["update-grant"];
        trace?: never;
    };
    "/applications/{app_id}/licenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants licensed for an application
         * @description Returns the tenants authorized to use an application.
         */
        get: operations["list-licenses"];
        put?: never;
        /**
         * Authorize a tenant for an application
         * @description Licenses a tenant to use the application. A user cannot be granted access in a tenant that is not licensed.
         */
        post: operations["authorize-license"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/licenses/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a tenant's license for an application
         * @description Removes a tenant's authorization to use the application.
         */
        delete: operations["revoke-license"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List application scopes
         * @description Returns the scope catalog defined for an application.
         */
        get: operations["list-scopes"];
        put?: never;
        /**
         * Define an application scope
         * @description Adds a scope to an application's catalog. Scopes are opaque permission strings the application interprets itself.
         */
        post: operations["create-scope"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/scopes/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an application scope
         * @description Removes a scope from the catalog. Any tier features referencing it are cascaded automatically.
         */
        delete: operations["delete-scope"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/tiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List application tiers
         * @description Returns the subscription tiers defined for an application, ordered by rank.
         */
        get: operations["list-tiers"];
        put?: never;
        /**
         * Define an application tier
         * @description Adds a subscription tier to an application. Bundle scopes into it via its features.
         */
        post: operations["create-tier"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/tiers/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an application tier
         * @description Removes a tier. Its feature bundles are cascaded; grants that referenced it keep their explicit scopes.
         */
        delete: operations["delete-tier"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/tiers/{tier_id}/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List scopes bundled into a tier
         * @description Returns the scopes bundled into a tier — the features every subscriber on this tier inherits.
         */
        get: operations["list-features"];
        put?: never;
        /**
         * Bundle a scope into a tier
         * @description Adds a scope to a tier's bundle. Users on the tier inherit it immediately — scope composition is dynamic.
         */
        post: operations["add-feature"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{app_id}/tiers/{tier_id}/features/{scope_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unbundle a scope from a tier
         * @description Removes a scope from a tier's bundle.
         */
        delete: operations["remove-feature"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List supported identity providers
         * @description Returns the external identity providers janus supports for account linking.
         */
        get: operations["list-providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenants
         * @description Returns a paginated list of all tenants. Use limit and offset to page.
         */
        get: operations["list-tenants"];
        put?: never;
        /**
         * Create a tenant
         * @description Creates a new customer organization.
         */
        post: operations["create-tenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search tenants
         * @description Query tenants with text search over name and slug, status faceting, date-range filters, sorting, and pagination. An empty body returns page 1, size 25, sorted updated_at desc, unfiltered.
         */
        post: operations["search-tenants"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a tenant
         * @description Fetches a single tenant by ID.
         */
        get: operations["get-tenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a tenant
         * @description Updates a tenant's name and status. Set status to 'suspended' to disable it.
         */
        patch: operations["update-tenant"];
        trace?: never;
    };
    "/tenants/{tenant_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tenant members
         * @description Returns the members of a tenant with their roles, paginated.
         */
        get: operations["list-members"];
        put?: never;
        /**
         * Add a tenant member
         * @description Adds a user to a tenant with a role (viewer, editor, admin, or owner).
         */
        post: operations["add-member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tenant member
         * @description Removes a user from a tenant. Removing the last owner is rejected.
         */
        delete: operations["remove-member"];
        options?: never;
        head?: never;
        /**
         * Update a member's role
         * @description Changes a member's role within a tenant. Demoting the last owner is rejected.
         */
        patch: operations["update-member-role"];
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a paginated list of users. Pass email to look up a single user by address.
         */
        get: operations["list-users"];
        put?: never;
        /**
         * Create a user
         * @description Creates a user directly. Normally users are provisioned automatically via the OIDC login flow.
         */
        post: operations["create-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search users
         * @description Query users with text search over email and display name, status faceting, date-range filters, sorting, and pagination. An empty body returns page 1, size 25, sorted updated_at desc, unfiltered.
         */
        post: operations["search-users"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a user
         * @description Fetches a single user by ID.
         */
        get: operations["get-user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a user
         * @description Updates a user's display name and status. Set status to 'inactive' to disable the account.
         */
        patch: operations["update-user"];
        trace?: never;
    };
    "/users/{user_id}/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a user's linked accounts
         * @description Returns the external identity-provider accounts linked to a user.
         */
        get: operations["list-user-accounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unlink a user's account
         * @description Removes a linked external account from a user.
         */
        delete: operations["unlink-user-account"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a user's sessions
         * @description Returns the active sessions for a user.
         */
        get: operations["list-user-sessions"];
        put?: never;
        post?: never;
        /**
         * Revoke all of a user's sessions
         * @description Revokes every active session for a user and returns the count revoked.
         */
        delete: operations["revoke-all-user-sessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a user's session
         * @description Revokes a single session by ID.
         */
        delete: operations["revoke-user-session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountListResponse: {
            /** @description Linked accounts */
            accounts: components["schemas"]["AccountResponse"][];
        };
        AccountResponse: {
            /**
             * @description External subject ID
             * @example gh-123
             */
            external_subject: string;
            /**
             * @description Account ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description When the account was linked
             * @example 2026-05-01T12:00:00Z
             */
            linked_at: string;
            /**
             * @description Identity provider
             * @example github
             */
            provider: string;
        };
        AddFeatureRequest: {
            /**
             * @description Scope ID to bundle into the tier
             * @example aa0e8400-e29b-41d4-a716-446655440000
             */
            scope_id: string;
        };
        AddMemberRequest: {
            /**
             * @description Role to assign
             * @example viewer
             */
            role: string;
            /**
             * @description User ID to add
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            user_id: string;
        };
        ApplicationListResponse: {
            /** @description Applications */
            applications: components["schemas"]["ApplicationResponse"][];
        };
        ApplicationResponse: {
            /**
             * @description Creation timestamp (RFC 3339)
             * @example 2026-01-01T00:00:00Z
             */
            created_at: string;
            /**
             * @description Application ID
             * @example 770e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Application name
             * @example Nexus
             */
            name: string;
            /**
             * @description Application slug
             * @example nexus
             */
            slug: string;
            /**
             * @description Application status
             * @example active
             */
            status: string;
            /**
             * @description Last update timestamp (RFC 3339)
             * @example 2026-08-21T00:00:00Z
             */
            updated_at: string;
        };
        ApplicationSearchResponse: {
            /** @description Matching applications for this page */
            applications: components["schemas"]["ApplicationResponse"][];
            /** @description Distinct facet values present in the filtered set */
            facets: {
                [key: string]: string[];
            };
            /** @description Pagination metadata */
            page: components["schemas"]["PageResponse"];
        };
        AuthorizeLicenseRequest: {
            /**
             * @description Tenant ID to authorize
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            tenant_id: string;
        };
        CreateApplicationRequest: {
            /**
             * @description Application name
             * @example Nexus
             */
            name: string;
            /**
             * @description URL-safe slug (matches the service cert CN)
             * @example nexus
             */
            slug: string;
        };
        CreateGrantRequest: {
            /** @description Application-defined roles */
            roles: string[];
            /** @description Application-defined scopes */
            scopes: string[];
            /**
             * @description Tenant the access is scoped to
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            tenant_id: string;
            /** @description Optional tier to place the grant on */
            tier_id?: string;
            /**
             * @description User ID to grant access to
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            user_id: string;
        };
        CreateScopeRequest: {
            /**
             * @description Human-readable description
             * @example Read projects
             */
            description: string;
            /**
             * @description Scope name
             * @example projects:read
             */
            name: string;
        };
        CreateTenantRequest: {
            /**
             * @description Tenant name
             * @example Acme Corp
             */
            name: string;
            /**
             * @description URL-safe tenant slug
             * @example acme-corp
             */
            slug: string;
        };
        CreateTierRequest: {
            /**
             * @description Tier display name
             * @example Pro
             */
            name: string;
            /**
             * @description Ordering rank (ascending)
             * @example 1
             */
            rank: number;
            /**
             * @description URL-safe tier slug
             * @example pro
             */
            slug: string;
        };
        CreateUserRequest: {
            /**
             * @description Display name
             * @example Jane Doe
             */
            display_name: string;
            /**
             * @description Email address
             * @example jane@example.com
             */
            email: string;
        };
        DateRange: {
            /**
             * Format: date-time
             * @description Inclusive lower bound (RFC 3339)
             * @example 2026-01-01T00:00:00Z
             */
            from?: string;
            /**
             * Format: date-time
             * @description Inclusive upper bound (RFC 3339)
             * @example 2026-08-21T00:00:00Z
             */
            to?: string;
        };
        ErrForbidden: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "FORBIDDEN";
            details?: {
                reason?: string;
            };
            /** @description Human-readable error message */
            message: string;
        };
        ErrNotFound: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "NOT_FOUND";
            details?: {
                resource?: string;
            };
            /** @description Human-readable error message */
            message: string;
        };
        ErrValidationFailed: {
            /**
             * @description Machine-readable error code
             * @constant
             */
            code: "VALIDATION_FAILED";
            details?: {
                fields: components["schemas"]["ValidationFieldError"][];
            };
            /** @description Human-readable error message */
            message: string;
        };
        FeatureListResponse: {
            /** @description Scopes bundled into the tier */
            features: components["schemas"]["FeatureResponse"][];
        };
        FeatureResponse: {
            /**
             * @description When the scope was bundled
             * @example 2026-07-12T12:00:00Z
             */
            created_at: string;
            /**
             * @description Feature ID
             * @example cc0e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Scope ID
             * @example aa0e8400-e29b-41d4-a716-446655440000
             */
            scope_id: string;
            /**
             * @description Tier ID
             * @example bb0e8400-e29b-41d4-a716-446655440000
             */
            tier_id: string;
        };
        GrantListResponse: {
            /** @description User grants */
            grants: components["schemas"]["GrantResponse"][];
        };
        GrantResponse: {
            /**
             * @description Application (label)
             * @example nexus
             */
            application: string;
            /**
             * @description When access was granted
             * @example 2026-05-01T12:00:00Z
             */
            created_at: string;
            /**
             * @description Grant ID
             * @example 990e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @description Application-defined roles */
            roles: string[];
            /** @description Application-defined scopes */
            scopes: string[];
            /**
             * @description Tenant ID
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            tenant_id: string;
            /** @description Tier the grant is on, if any */
            tier_id?: string;
            /**
             * @description User ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            user_id: string;
        };
        LicenseListResponse: {
            /** @description Licenses */
            licenses: components["schemas"]["LicenseResponse"][];
        };
        LicenseResponse: {
            /**
             * @description Application (label)
             * @example nexus
             */
            application: string;
            /**
             * @description When the license was granted
             * @example 2026-05-01T12:00:00Z
             */
            created_at: string;
            /**
             * @description License ID
             * @example 880e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Tenant ID
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            tenant_id: string;
        };
        MemberListResponse: {
            /** @description Tenant members */
            members: components["schemas"]["MemberResponse"][];
            /**
             * @description Total member count
             * @example 7
             */
            total: number;
        };
        MemberResponse: {
            /**
             * @description When the membership was created
             * @example 2026-05-01T12:00:00Z
             */
            created_at: string;
            /**
             * @description Membership ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Role
             * @example admin
             */
            role: string;
            /**
             * @description Tenant ID
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            tenant_id: string;
            /**
             * @description User ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            user_id: string;
        };
        NoBody: Record<string, never>;
        PageRequest: {
            /**
             * @description 1-based page number (default 1)
             * @example 1
             */
            number?: number;
            /**
             * @description Page size, 1-100 (default 25)
             * @example 25
             */
            size?: number;
        };
        PageResponse: {
            /**
             * @description Current page number
             * @example 1
             */
            number: number;
            /**
             * @description Page size
             * @example 25
             */
            size: number;
            /**
             * @description Total items across all pages
             * @example 57
             */
            total_items: number;
            /**
             * @description Total number of pages
             * @example 3
             */
            total_pages: number;
        };
        ProviderListResponse: {
            /**
             * @description Supported identity providers
             * @example [
             *       "zitadel"
             *     ]
             */
            providers: string[];
        };
        RevokeAllSessionsResponse: {
            /**
             * @description Number of sessions revoked
             * @example 3
             */
            revoked_count: number;
        };
        ScopeListResponse: {
            /** @description Application scopes */
            scopes: components["schemas"]["ScopeResponse"][];
        };
        ScopeResponse: {
            /**
             * @description Owning application (label)
             * @example nexus
             */
            application: string;
            /**
             * @description When the scope was defined
             * @example 2026-07-12T12:00:00Z
             */
            created_at: string;
            /**
             * @description Human-readable description
             * @example Read projects
             */
            description: string;
            /**
             * @description Scope ID
             * @example aa0e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Scope name
             * @example projects:read
             */
            name: string;
        };
        SearchApplicationsRequest: {
            /** @description Inclusive date-range filters keyed by field */
            dates?: {
                [key: string]: components["schemas"]["DateRange"];
            };
            /** @description Field-scoped filters: OR within a field, AND across fields */
            facets?: {
                [key: string]: string[];
            };
            /** @description Pagination window (default page 1, size 25) */
            page?: components["schemas"]["PageRequest"];
            /**
             * @description Case-insensitive infix match over name and slug
             * @example acme
             */
            query?: string;
            /** @description Sort specification (default updated_at desc) */
            sort?: components["schemas"]["SortSpec"];
        };
        SearchTenantsRequest: {
            /** @description Inclusive date-range filters keyed by field */
            dates?: {
                [key: string]: components["schemas"]["DateRange"];
            };
            /** @description Field-scoped filters: OR within a field, AND across fields */
            facets?: {
                [key: string]: string[];
            };
            /** @description Pagination window (default page 1, size 25) */
            page?: components["schemas"]["PageRequest"];
            /**
             * @description Case-insensitive infix match over name and slug
             * @example acme
             */
            query?: string;
            /** @description Sort specification (default updated_at desc) */
            sort?: components["schemas"]["SortSpec"];
        };
        SearchUsersRequest: {
            /** @description Inclusive date-range filters keyed by field */
            dates?: {
                [key: string]: components["schemas"]["DateRange"];
            };
            /** @description Field-scoped filters: OR within a field, AND across fields */
            facets?: {
                [key: string]: string[];
            };
            /** @description Pagination window (default page 1, size 25) */
            page?: components["schemas"]["PageRequest"];
            /**
             * @description Case-insensitive infix match over email and display name
             * @example jane
             */
            query?: string;
            /** @description Sort specification (default updated_at desc) */
            sort?: components["schemas"]["SortSpec"];
        };
        SessionListResponse: {
            /** @description Active sessions */
            sessions: components["schemas"]["SessionResponse"][];
        };
        SessionResponse: {
            /**
             * @description When the session was created
             * @example 2026-05-01T12:00:00Z
             */
            created_at: string;
            /**
             * @description When the session expires
             * @example 2026-05-02T12:00:00Z
             */
            expires_at: string;
            /**
             * @description Session ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Last known IP
             * @example 192.168.1.1
             */
            ip_address?: string;
            /**
             * @description Service that created the session
             * @example nexus
             */
            issued_by: string;
            /**
             * @description Device/browser info
             * @example Mozilla/5.0
             */
            user_agent?: string;
        };
        SortSpec: {
            /**
             * @description Field to sort by
             * @example created_at
             */
            field: string;
            /**
             * @description Sort direction: asc or desc
             * @example desc
             */
            order: string;
        };
        TenantListResponse: {
            /** @description Tenants */
            tenants: components["schemas"]["TenantResponse"][];
            /**
             * @description Total tenant count
             * @example 42
             */
            total: number;
        };
        TenantResponse: {
            /**
             * @description Tenant ID
             * @example 660e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Tenant name
             * @example Acme Corp
             */
            name: string;
            /**
             * @description Tenant slug
             * @example acme-corp
             */
            slug: string;
            /**
             * @description Tenant status
             * @example active
             */
            status: string;
        };
        TenantSearchResponse: {
            /** @description Distinct facet values present in the filtered set */
            facets: {
                [key: string]: string[];
            };
            /** @description Pagination metadata */
            page: components["schemas"]["PageResponse"];
            /** @description Matching tenants for this page */
            tenants: components["schemas"]["TenantResponse"][];
        };
        TierListResponse: {
            /** @description Application subscription tiers */
            tiers: components["schemas"]["TierResponse"][];
        };
        TierResponse: {
            /**
             * @description Owning application (label)
             * @example nexus
             */
            application: string;
            /**
             * @description When the tier was defined
             * @example 2026-07-12T12:00:00Z
             */
            created_at: string;
            /**
             * @description Tier ID
             * @example bb0e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Tier display name
             * @example Pro
             */
            name: string;
            /**
             * @description Ordering rank
             * @example 1
             */
            rank: number;
            /**
             * @description Tier slug
             * @example pro
             */
            slug: string;
        };
        UpdateApplicationRequest: {
            /**
             * @description Application name
             * @example Nexus
             */
            name: string;
            /**
             * @description Application status
             * @example active
             */
            status: string;
        };
        UpdateGrantRequest: {
            /** @description Application-defined roles */
            roles: string[];
            /** @description Application-defined scopes */
            scopes: string[];
            /** @description Tier to place the grant on (empty clears it) */
            tier_id?: string;
        };
        UpdateMemberRoleRequest: {
            /**
             * @description New role
             * @example admin
             */
            role: string;
        };
        UpdateTenantRequest: {
            /**
             * @description Tenant name
             * @example Acme Corp
             */
            name: string;
            /**
             * @description Tenant status
             * @example active
             */
            status: string;
        };
        UpdateUserRequest: {
            /**
             * @description Display name
             * @example Jane Doe
             */
            display_name: string;
            /**
             * @description Account status
             * @example active
             */
            status: string;
        };
        UserListResponse: {
            /**
             * @description Total user count
             * @example 128
             */
            total: number;
            /** @description Users */
            users: components["schemas"]["UserResponse"][];
        };
        UserResponse: {
            /**
             * @description When the user was created
             * @example 2026-05-01T12:00:00Z
             */
            created_at: string;
            /**
             * @description Display name
             * @example Jane Doe
             */
            display_name: string;
            /**
             * @description Email address
             * @example jane@example.com
             */
            email: string;
            /**
             * @description User ID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description When the user was last seen
             * @example 2026-07-12T12:00:00Z
             */
            last_seen_at?: string;
            /**
             * @description Account status
             * @example active
             */
            status: string;
        };
        UserSearchResponse: {
            /** @description Distinct facet values present in the filtered set */
            facets: {
                [key: string]: string[];
            };
            /** @description Pagination metadata */
            page: components["schemas"]["PageResponse"];
            /** @description Matching users for this page */
            users: components["schemas"]["UserResponse"][];
        };
        ValidationFieldError: {
            /** @description The field that failed validation */
            field: string;
            /** @description Description of the validation failure */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
        };
    };
    "create-application": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "search-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchApplicationsRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationSearchResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "get-application": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "update-application": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "list-grants": {
        parameters: {
            query?: {
                tenant_id?: string;
            };
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantListResponse"];
                };
            };
        };
    };
    "create-grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "revoke-grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "update-grant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGrantRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "list-licenses": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenseListResponse"];
                };
            };
        };
    };
    "authorize-license": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizeLicenseRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LicenseResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "revoke-license": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "list-scopes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeListResponse"];
                };
            };
        };
    };
    "create-scope": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScopeRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScopeResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "delete-scope": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "list-tiers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierListResponse"];
                };
            };
        };
    };
    "create-tier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTierRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TierResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "delete-tier": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "list-features": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureListResponse"];
                };
            };
        };
    };
    "add-feature": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFeatureRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "remove-feature": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                app_id: string;
                tier_id: string;
                scope_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "list-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
        };
    };
    "list-tenants": {
        parameters: {
            query?: {
                limit?: string;
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantListResponse"];
                };
            };
        };
    };
    "create-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "search-tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchTenantsRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSearchResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "get-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "update-tenant": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTenantRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "list-members": {
        parameters: {
            query?: {
                limit?: string;
                offset?: string;
            };
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
        };
    };
    "add-member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "remove-member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrForbidden"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "update-member-role": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrForbidden"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "list-users": {
        parameters: {
            query?: {
                email?: string;
                limit?: string;
                offset?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
        };
    };
    "create-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Success */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "search-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchUsersRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSearchResponse"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "get-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "update-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
            /** @description UnprocessableEntity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrValidationFailed"];
                };
            };
        };
    };
    "list-user-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    "unlink-user-account": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
    "list-user-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
        };
    };
    "revoke-all-user-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevokeAllSessionsResponse"];
                };
            };
        };
    };
    "revoke-user-session": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoBody"];
                };
            };
            /** @description NotFound */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrNotFound"];
                };
            };
        };
    };
}
